from django.urls import path

from .views import *
urlpatterns = [
    path('account_customusers/', AccountCustomUserListView.as_view(), name='account_customusers-list'),
    path('account_customusers/<int:pk>/', AccountCustomUserDetailView.as_view(), name='accountcustomuser-detail'),
    path('account_invitations/', AccountsInvitationListView.as_view(), name='accountInvitation-list'),
    path('account_invitations/<int:pk>/', AccountsInvitationDetailView.as_view(), name='accountsinvitation-detail'),
    path('news_items/', NewsItemListView.as_view(), name='newsItem-list'),
    path('news_items/<int:pk>/', NewsItemDetailView.as_view(), name='newsitem-detail'),
    path('news_votes/', NewsVoteListView.as_view(), name='newsVote-list'),
    path('news_votes/<int:pk>/', NewsVoteDetailView.as_view(), name='newsvote-detail'),
    path('news_stories/', NewsStoryListView.as_view(), name='newsStory-list'),
    path('news_stories/<int:pk>/', NewsStoryDetailView.as_view(), name='newsstory-detail'),
    path('news_comments/', NewsCommentListView.as_view(), name='newsComment-list'),
    path('news_comments/<int:pk>/', NewsCommentDetailView.as_view(), name='newsComment-detail'),
    path('email_digest_subscriptions/', EmailDigestSubscriptionListView.as_view(), name='ED_subscription-list'),
    path('email_digest_subscriptions/<int:pk>/', EmailDigestSubscriptionDetailView.as_view(),
         name='emaildigestsubscription-detail'),
    path('email_digest_email_digests/', EmailDigestEmailDigestListView.as_view(), name='emailDigestEmailDigest-list'),
    path('email_digest_email_digests/<int:pk>/', EmailDigestEmailDigestDetailView.as_view(),
         name='emailDigestEmailDigest-detail'),
    path('email_digest_un_subscriptions/', EmailDigestUnsubscriptionListView.as_view(), name='unsubscription-list'),
    path('email_digest_un_subscriptions/<int:pk>/', EmailDigestUnsubscriptionDetailView.as_view(),
         name='unsubscription-detail'),
    path('email_digest_email_digest_stories/', EmailDigestEmailDigestStoriesListView.as_view(), name='stories-list'),
    path('email_digest_email_digest_stories/<int:pk>/', EmailDigestEmailDigestStoriesDetailView.as_view(),
         name='stories-detail'),
    path('email_digest_user_subscriptions/', EmailDigestUserSubscriptionListView.as_view(), name='user_sub-list'),
    path('email_digest_user_subscriptions/<int:pk>/', EmailDigestUserSubscriptionDetailView.as_view(),
         name='user_sub-detail'),
    path('email_digest_anonymous_subscriptions/', EmailDigestAnonymousSubscriptionListView.as_view(),
         name='anonymous_subscription-list'),
    path('email_digest_anonymous_subscriptions/<int:pk>/', EmailDigestAnonymousSubscriptionDetailView.as_view(),
         name='anonymous-list'),
    path('account_email_verifications/', AccountsEmailVerificationListView.as_view(), name='verifications-list'),
    path('account_email_verifications/<int:pk>/', AccountsEmailVerificationDetailView.as_view(),
         name='accountsemailverification-detail'),
    path('account_password_rest_requests/', AccountPasswordResetRequestListView.as_view(), name='rest_password-list'),
    path('account_password_rest_requests/<int:pk>/', AccountPasswordResetRequestDetailView.as_view(),
         name='rest_password-detail'),
    path('django_content_types/', DjangoContentTypeListView.as_view(), name='django_content_type-list'),
    path('django_content_types/<int:pk>/', DjangoContentTypeDetailView.as_view(), name='djangocontenttype-detail'),
    path('auth_permissions/', AuthPermissionListView.as_view(), name='auth_permissions-list'),
    path('auth_permissions/<int:pk>/', AuthPermissionDetailView.as_view(), name='authpermission-detail'),
    path('auth_groups/', AuthGroupListView.as_view(), name='auth_group-list'),
    path('auth_groups/<int:pk>/', AuthGroupDetailView.as_view(), name='auth_group-detail'),
    path('django_admin_log/', DjangoAdminLogListView.as_view(), name='django_admin_log-list'),
    path('django_admin_log/<int:pk>/', DjangoAdminLogDetailView.as_view(), name='djangoadminlog-detail')
]

