# Generated by my_content 4.2.3 on 2023-09-05 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='user name')),
                ('email', models.CharField(max_length=32, verbose_name='email')),
                ('password', models.CharField(max_length=12, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='last name')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is superuser')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('karma', models.IntegerField(blank=True, default=0, null=True, verbose_name='karma')),
                ('about', models.TextField(blank=True, verbose_name='about')),
                ('level', models.IntegerField(verbose_name='level')),
                ('left', models.IntegerField(blank=True, null=True, verbose_name='left')),
                ('right', models.IntegerField(blank=True, null=True, verbose_name='right')),
                ('tree_id', models.IntegerField(blank=True, null=True, verbose_name='tree id')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
            ],
        ),
        migrations.CreateModel(
            name='AccountsInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.IntegerField(verbose_name='invite code')),
                ('invited_email_address', models.CharField(blank=True, max_length=32, verbose_name='invited email address')),
                ('num_signups', models.IntegerField(blank=True, null=True, verbose_name='num signups')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='changed at')),
            ],
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('codename', models.CharField(max_length=32, verbose_name='code name')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_content.djangocontenttype')),
                ('custom_user', models.ManyToManyField(to='hacker_news.accountcustomuser')),
            ],
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('custom_user', models.ManyToManyField(to='hacker_news.accountcustomuser')),
                ('permission', models.ManyToManyField(to='hacker_news.authpermission')),
            ],
        ),
        migrations.CreateModel(
            name='AccountsEmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('verification_code', models.CharField(max_length=32, verbose_name='verification code')),
                ('email', models.CharField(max_length=32, verbose_name='email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hacker_news.accountcustomuser')),
            ],
        ),
        migrations.CreateModel(
            name='AccountPasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_code', models.CharField(max_length=32, verbose_name='verified code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hacker_news.accountcustomuser')),
            ],
        ),
        migrations.AddField(
            model_name='accountcustomuser',
            name='used_invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hacker_news.accountsinvitation'),
        ),
    ]
